DROP EXTENSION IF EXISTS pgcrypto;

DROP TABLE IF EXISTS payment_schedules CASCADE;
DROP TABLE IF EXISTS credits CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS cards CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS users CASCADE;