CREATE TABLE IF NOT EXISTS users (
    id SERIAL  PRIMARY KEY,
    username   VARCHAR(50) UNIQUE NOT NULL,
    email      VARCHAR(100) UNIQUE NOT NULL,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS accounts (
    id SERIAL  PRIMARY KEY,
    user_id    INTEGER REFERENCES users(id) ON DELETE CASCADE,
    balance    NUMERIC(12,2) DEFAULT 0,
    currency   CHAR(3) NOT NULL DEFAULT 'RUB',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE INDEX idx_accounts_user_id ON accounts(user_id);

CREATE TABLE IF NOT EXISTS cards (
    id SERIAL PRIMARY KEY,
    account_id INTEGER REFERENCES accounts(id) ON DELETE CASCADE,
    number VARCHAR(20) UNIQUE NOT NULL,
    cvv VARCHAR(4) NOT NULL,
    expiry DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE INDEX idx_cards_account_id ON cards(account_id);

CREATE TABLE IF NOT EXISTS transactions (
    id SERIAL PRIMARY KEY,
    account_from INTEGER REFERENCES accounts(id) ON DELETE SET NULL,
    account_to INTEGER REFERENCES accounts(id) ON DELETE SET NULL,
    amount NUMERIC(12,2) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL CHECK(transaction_type IN ('transfer', 'deposit', 'withdrawal', 'payment')),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
CREATE INDEX idx_transactions_date ON transactions(transaction_date);

CREATE TABLE credits
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id    BIGINT         NOT NULL REFERENCES accounts (id) ON DELETE CASCADE,
    principal     NUMERIC(12, 2) NOT NULL,
    interest_rate NUMERIC(5, 4)  NOT NULL,
    term_months   INT            NOT NULL,
    start_date    DATE           NOT NULL,
    status        VARCHAR(20)    NOT NULL DEFAULT 'active',
    created_at    TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_credits_account_id ON credits (account_id);

CREATE TABLE payment_schedules
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    credit_id  BIGINT         NOT NULL REFERENCES credits (id) ON DELETE CASCADE,
    due_date   DATE           NOT NULL,
    amount     NUMERIC(12, 2) NOT NULL,
    paid       BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_schedule_credit_id ON payment_schedules (credit_id);

